E2Helper.Descriptions["createField(vvsn)"] = "Creates a field at position pos of size size with type type which inflict damage damage per second and returns the id of the field\nAllowed types are:\n\tradiation"
E2Helper.Descriptions["setFieldPos(nv)"] = "Sets the position of the field n to the position pos"
E2Helper.Descriptions["setFieldSize(nv)"] = "Sets the size of the field n to size"
E2Helper.Descriptions["setFieldType(ns)"] = "Sets the type of the field n to type"
E2Helper.Descriptions["setFieldDamage(nn)"] = "Sets the damage don per second of the field n to damage"
E2Helper.Descriptions["getFieldTypes()"] = "Returns a table with all possible field types"
E2Helper.Descriptions["deleteAllFields()"] = "Deletes all fields"
E2Helper.Descriptions["deleteField(n)"] = "Deletes the field with the id id"